name: Deploy Backend

on:
  push:
    branches: [ "main" ]
    paths: [ "backend/**" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: us-east-1
    - name: Connect to EKS Cluster
      run: aws eks update-kubeconfig --name cluster --region us-east-1
    - name: Deploy to Kubernetes
      run: kubectl apply -f backend/
